AMQP_URI: amqp://${RABBIT_USER:guest}:${RABBIT_PASSWORD:guest}@${RABBIT_HOST:localhost}:${RABBIT_PORT:5672}/
max_workers: 10
parent_calls_tracked: 10

LOGGING:
    version: 1
    handlers:
        console:
            class: logging.StreamHandler
        info_file_handler:
            class: logging.handlers.RotatingFileHandler
            level: DEBUG
            filename: nameko.log
    root:
        level: DEBUG
        handlers: [console, info_file_handler]