version: "3"
services:
  rabbitmq:
    container_name: sms-octopus-rabbitmq
    container_name: nameko-example-rabbitmq
    image: rabbitmq:3.7-management
    ports:
        - "5672:5672"
        - "5671:5671"
        - "15672:15672"
